blank_issues_enabled: false
contact_links:
    -   name: Bug Report
        url: https://github.com/isaeken/laravel-backup/issues/new
        about: Report a bug
    -   name: Feature Request
        url: https://github.com/isaeken/laravel-backup/discussions/new
        about: Share ideas for new features
    -   name: Ask a Question
        url: https://github.com/isaeken/laravel-backup/discussions/new
        about: Ask the community for help
